using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Number.Db
{
    public class Input
    {
        [Key]
        public int Id { get; set; }
        [Required]
        ///<summary>
        /// The beginning of Fibonacci generation sequence
        ///</summary>
        public int FirstIndex { get; set; }
        [Required]
        ///<summary>
        /// The end of Fibonacci generation sequence
        ///</summary>
        public int LastIndex { get; set; }
        ///<summary>
        /// If user wants to enable caching feature of application
        ///</summary>
        public bool isCached { get; set; }
        ///<summary>
        /// To be able to stop application if generation of first value
        /// of the sequence takes more than value stored in this property
        ///</summary>
        public TimeSpan Time { get; set; }
        ///<summary>
        /// To be able to sop application from execution if amount of
        /// memory in bytes is exceeding provided by user value
        ///</summary>
        public int MemoryUsage { get; set; }
        ///<summary>
        ///  Fibonacci sequence generated by the API
        ///</summary>
        public List<int> FibSequence { get; set; }
    }
}
